server: 
  port: 8201 
spring:
  application:
  	profiles: dev
    name:  microservicecloud-config-client

 
eureka:
  client: 
  	service url:
  	  defaultZone: http://eureka-dev.com:7001/eureka/
---
server: 
  port: 8202 

spring:
  application:
  	profiles: test
    name:  microservicecloud-config-client

eureka:
  client: 
  	service url:
  	  defaultZone: http://eureka-test.com:7001/eureka/
